name: Genesis OS Full Auto Build & Assemble

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write

    env:
      # Set up Android SDK path for local.properties
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Set up Gradle 8.14.3
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.14.3

    - name: Set up Android SDK (API 34)
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        sdk-tools: 'platform-tools,build-tools;34.0.0'

    - name: Create local.properties
      run: |
        echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties

    - name: Cache Gradle and Kotlin
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.toml') }}

    - name: Grant Execute Permission to Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Build Artifacts (APK/JAR/AAR)
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/debug/*.apk
          **/build/libs/*.jar
          **/build/outputs/**/*.aar

    - name: Lint and Code Style (ktlint)
      run: ./gradlew ktlintCheck

    - name: Run Tests
      run: ./gradlew testDebugUnitTest
